### ISSUE TITLE
Question about parallel running

### ISSUE THREAD

**Issue by AdamReece-WebBox** [shapecode/cron-bundle#12]
Hello,

Firstly, thank you for this bundle. This certainly makes Symfony based CRON jobs for projects easier. (Knocked up a basic CMS interface to read, run, rescan, and enable/disable for added usefulness.)

We have a question about CRONs running in parallel. -- What happens if a command has a schedule for every 10 minutes, but takes longer than 10 minutes to run due to unpredicted delays?

When the 20th minute comes along to run the command for a second time, does this bundle notice that the first one is still running and knows not to spawn another instance in parallel, or would another instance be run?

I ask because certain commands could become problematic when race conditions occur due to parallel runs. I am guessing this can happen with this bundle as I've not seen enough information in the 2 entity tables that could even allow the runner to detect that a command is already running.

Is an option for how to handle parallel instances (such as that in Windows Task Scheduler shown below) within future scope, or should we do something externally to prevent parallel runs?

![image](https://user-images.githubusercontent.com/16222407/45878311-8642bf00-bd98-11e8-9e0e-0d0c18341d1b.png)

An implementation within the bundle could potentially be to create the CronJobResult entity at the start of the run instead of on completion, but leaving particular properties (such as `run_time` and `status_code` as NULL until the run has completed. That way when the runner begins to run a command it could check if an existing CronJobResult entity exists for the command but with a NULL `run_time` or `status_code`.

Doing something externally (e.g. a "run" file) might not work well if the command closes due to an error, whereas (in many cases) this bundle's runner would be able to hear when a command closes due to an error. -- With the exception of external terminations (or power cuts) of course...

**Comment by nicklog** [comment]
Hey
Sorry you had to wait so long for an answer. I was on vacation.

> We have a question about CRONs running in parallel. -- What happens if a command has a schedule for every 10 minutes, but takes longer than 10 minutes to run due to unpredicted delays? When the 20th minute comes along to run the command for a second time, does this bundle notice that the first one is still running and knows not to spawn another instance in parallel, or would another instance be run?

The CronJob should be skipped. If this is not the case, a change is possible. I'm currently no longer so in the topic and would have to look at it in detail first.

**Comment by AdamReece-WebBox** [comment]
Hello,
No problem - everyone deserves a fair break. :)

> The CronJob should be skipped

Ah okay, so a parallel job won't start. -- That is actually what we want in this case.

I'm wondering how the bundle can determine this. I didn't think there was enough information in the entities alone to do this, are you inspecting other running PHP processes or using PID files or similar?

**Comment by nicklog** [comment]
I have checked it and there is no check. It would start a parallel job. Your case has to be implemented first.

**Comment by nicklog** [comment]
Take a look into the new "3.3 Dev Release".
Mark your CronJobs like this: @CronJob("@hourly", maxInstances=3)
Or leave them as they are. Then only one instance runs at a time.

**Comment by AdamReece-WebBox** [comment]
Thanks for the `maxInstances` parameter. 👍
