### ISSUE TITLE
maxInstances Annotation produces error

### ISSUE THREAD

**Issue by PandyLegend** [shapecode/cron-bundle#27]
When using maxInstances in the annotation, such as `@CronJob("*\/5 * * * *",maxInstances=2)`
upon running `php bin/console shapecode:cron:scan` I get the following error:

> In Annotation.php line 75:
>
>  Unknown property 'maxInstances' on annotation 'Shapecode\Bundle\CronBundle\
>  Annotation\CronJob'.

As far as I can tell, the code in src/Annotation/CronJob.php is correct and I even get the typehint for maxInstances in PHPStorm.
As this doesn't appear in the docs, it's possible that I am doing something wrong - if so, could you advise and update the docs accordingly?
Thanks

**Comment by nicklog** [comment]
Thanks for your PR. I'll take a look by time.

**Comment by nicklog** [comment]
Test it if you want and then close this issue. thank you :)

**Comment by PandyLegend** [comment]
All seems good! Thanks
