### ISSUE TITLE
shapecode:crone:run --no-sleep

### ISSUE THREAD

**Issue by Bast1onCZ** [shapecode/cron-bundle#32]
Hello, could you please add an option like `--no-sleep` to command `shapecode:crone:run`? I'd love to run the cron very often, but I don't like the idea of having frozen app for such a long time.

Thank you very much!

**Comment by nicklog** [comment]
@Bast1onCZ What exactly should this option do?

**Comment by Bast1onCZ** [comment]
@nicklog when using `shapecode:crone:run` a couple of months ago, I have noticed that the this library implementation uses `sleep` command. This migh be cool if the command is executed by user, but it is not very effective if you have plenty of commands run by cron
