### ISSUE TITLE
Declaration of Shapecode\Bundle\CronBundle\Console\Style\CronStyle is not compatible with Symfony 5.2

### ISSUE THREAD

**Issue by dkorsak** [shapecode/cron-bundle#35]
Full waring message:

Warning: Declaration of Shapecode\Bundle\CronBundle\Console\Style\CronStyle::info(string $message): void should be compatible with Symfony\Component\Console\Style\SymfonyStyle::info($message)   

Command: shapecode:cron:scan

**Comment by nicklog** [comment]
Yes, you are right. Its since Symfony 5.2. 
I'll make an update by time.
