### ISSUE TITLE
Cannot install on fresh Symfony 5.2 project

### ISSUE THREAD

**Issue by lars-feyerabend** [shapecode/cron-bundle#36]
Hi there,

installing this bundle on a fresh Symfony 5.2 project (v5.2.1, created with "symfony new --full" today) like described in the docs yields the following error:

```
❯ composer require shapecode/cron-bundle
Using version ^4.0 for shapecode/cron-bundle
./composer.json has been updated
Running composer update shapecode/cron-bundle
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - shapecode/cron-bundle[4.0.0, ..., 4.0.3] require doctrine/persistence ^1.2 -> found doctrine/persistence[1.2.0, ..., 1.4.x-dev] but the package is fixed to 2.1.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires shapecode/cron-bundle ^4.0 -> satisfiable by shapecode/cron-bundle[4.0.0, 4.0.1, 4.0.2, 4.0.3].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

It seems like 5.2 requires `doctrine/orm ^2.8` which made the switch to `doctrine/persistence ^2`:

```
❯ composer why-not doctrine/persistence ^1.2
doctrine/common          3.1.0   requires  doctrine/persistence (^2.0)
doctrine/orm             2.8.1   requires  doctrine/persistence (^2.0)
symfony/doctrine-bridge  v5.2.1  requires  doctrine/persistence (^2)
```

Could you maybe check if upgrading the project to `doctrine/persistence ^2` is possible?

**Comment by lars-feyerabend** [comment]
I'm sorry, I got mixed up in my attempted upgrade chaos. In `dev-master`, `doctrine/persistence` is already allowed at `2.0`, but `doctrine/common` is still a problem:

```
❯ composer require shapecode/cron-bundle dev-master
./composer.json has been updated
Running composer update shapecode/cron-bundle
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires shapecode/cron-bundle dev-master -> satisfiable by shapecode/cron-bundle[dev-master].
    - shapecode/cron-bundle dev-master requires doctrine/common ^2.8 -> found doctrine/common[v2.8.0, ..., 2.13.x-dev] but the package is fixed to 3.1.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

```
❯ composer why-not doctrine/common ^2.8
doctrine/orm     2.8.1       requires          doctrine/common (^3.0)
...
```

**Comment by lars-feyerabend** [comment]
According to its [release notes](https://github.com/doctrine/common/releases/tag/3.0.0), `doctrine/common`s breaking change with the 3.x release was removing sub-dependencies. In `dev-master`, you're currently using the following classes from the `Doctrine\Common` namespace:

 * `Doctrine\Common\EventSubscriber`  
   (provided by `doctrine/event-manager`)

 * `Doctrine\Common\Collections\ArrayCollection`  
   `Doctrine\Common\Collections\Collection`  
   (provided by `doctrine/collections`)

 * `Doctrine\Common\Annotations\Annotation`  
   `Doctrine\Common\Annotations\AnnotationReader`  
   `Doctrine\Common\Annotations\Reader`  
   (provided by `doctrine/annotations`)

 * `Doctrine\Common\Persistence\Event\LifecycleEventArgs`  
   `Doctrine\Common\Persistence\ManagerRegistry`  
   `Doctrine\Common\Persistence\ObjectManager`  
   (provided by `doctrine/persistence` - `LifecycleEventArgs` seem fine, but I think the other two were missed when upgrading `doctrine/persistence` from `^1.2` to `^2.0`, they're used in `tests/Command/CronRunCommandTest.php`.)

So overall I think it's fine to remove the dependency on `doctrine/common` and replace it with the packages above.

**Comment by nicklog** [comment]
@lars-feyerabend Hey and thank you very much. I followed your advice and removed `doctrine/common` with minimal changes :)

**Comment by Gemorroj** [comment]
@nicklog can you release 4.x brunch with fixes for symfony 5.2?

**Comment by nicklog** [comment]
Ich did a backport. Take a look at v4.0.4

**Comment by Gemorroj** [comment]
@nicklog need upgrade `doctrine/persistence` at least.

**Comment by nicklog** [comment]
@Gemorroj Only for you <3 :zany_face: 
v4.0.5 is your friend.

**Comment by Gemorroj** [comment]
@nicklog thank you very much. Works for me =)
