### ISSUE TITLE
Remove unused method with code issue in CronJob::getInterval. 

### ISSUE THREAD

**Issue by jekk0** [shapecode/cron-bundle#37]
Hi there, 
I'm add custom logic around the package and working with model/repository directly, but when entity manager execute sql query(findAll, findBy etc.. ), application throw exception

`Fatal error: Uncaught Exception: DateInterval::__construct(): Unknown or bad format (* * * * *)`

Code for reproduce: `new DateInterval('* * * * *');`
Class: `CronJob`
Method: `getInterval`

**Comment by nicklog** [comment]
@jekk0 i removed it, thank you :)

**Comment by jekk0** [comment]
Thank you
