### ISSUE TITLE
Use $this->getContainer()->get('doctrine') give problem when command use cron generate error if command made doctrine error

### ISSUE THREAD

**Issue by Kleinast** [shapecode/cron-bundle#4]
Hi,

I have a custom command who eventually can generate doctrine error that I catch.
But apparently, even if I catch the error, the Entity Manager is closed (https://github.com/symfony/symfony/issues/5339), and it result that Cron Job result saved failed.

I think it's happen because you use directly 'doctrine' service instead of 'register' to get the Entity manager.

Does that problem speak to you ?

Thanks in advance

**Comment by nicklog** [comment]
I'll take look. which version do you use?

**Comment by Kleinast** [comment]
Here my composer.lock
"name": "shapecode/cron-bundle",
            "version": "2.1.0",
            "source": {
                "type": "git",
                "url": "https://github.com/shapecode/cron-bundle.git",
                "reference": "f6376a0b7a14f1036f44154ff7f572f19a45bad5"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/shapecode/cron-bundle/zipball/f6376a0b7a14f1036f44154ff7f572f19a45bad5",
                "reference": "f6376a0b7a14f1036f44154ff7f572f19a45bad5",
                "shasum": ""
            },

**Comment by nicklog** [comment]
hey, try the new 2.2 dev release.
