### ISSUE TITLE
release with php 8 support

### ISSUE THREAD

**Issue by Gemorroj** [shapecode/cron-bundle#42]
Сurrent stable release (4.0.5) doesn't support php 8
That would be nice release new version with php 8 support

**Comment by PEyacher** [comment]
+1 
@nicklog What is missing for a release compatible with PHP 8? Can we help making this happen?

**Comment by nicklog** [comment]
There is a 5.0-dev release that should be tested before.
If all works it can go to stable.

**Comment by NicoHaase** [comment]
Any news on this topic? We would love to use PHP 8 in one of our projects, but this bundle is one of the last packages we use without support :(

**Comment by nicklog** [comment]
I will check the 5er version later and release it 👍

**Comment by Gemorroj** [comment]
I use the master branch at least several months and didn't see any problems.

**Comment by nicklog** [comment]
@Gemorroj Thank you, for your feedback :)
