### ISSUE TITLE
Release with symfony 6 support

### ISSUE THREAD

**Issue by Gemorroj** [shapecode/cron-bundle#52]
Current stable version (5.0.1) doesn't support symfony 6.
But the "master" branch supports.

**Comment by nicklog** [comment]
If you want give it a try with the 6.0@dev release and give me feedback :)

**Comment by Gemorroj** [comment]
`6.0@dev` doesn't work but `6.0.x-dev` works.
```
  Problem 1
    - Root composer.json requires shapecode/cron-bundle 6.0@dev, found shapecode
/cron-bundle[dev-master, dev-release/4.0, dev-release/5.0, 1.0.0, ..., 1.3.4, 2.
0.0-beta1, 2.0.0-beta2, 2.0.0, 2.1.0, 3.0.0, ..., 3.2.3, 4.0.0, ..., 4.0.5, 5.0.
0, 5.0.1, 6.0.x-dev (alias of dev-master)] but it does not match the constraint.
```

**Comment by CaptainKant** [comment]
I would like try the dev-master version, but I can't import annotations anymore

**Comment by CaptainKant** [comment]
I would like to try the dev version, but annotations seems to be missing ?
No "Shapecode\Bundle\CronBundle\Annotation\CronJob" anymore

**Comment by nicklog** [comment]
Hey @CaptainKant 
Annotations have been replaced by attributes.

**Comment by CaptainKant** [comment]
> Hey @CaptainKant
> Annotations have been replaced by attributes.

Thanks. I juste made a PR to update readme.md with this info

**Comment by nicklog** [comment]
Thank you.

**Comment by nicklog** [comment]
@CaptainKant Please tell me about your experiences with v6.

**Comment by CaptainKant** [comment]
Hello all is OK, thank you !

**Comment by NicoHaase** [comment]
Any news on this topic? I'd love to upgrade to Symfony v6

**Comment by nicklog** [comment]
yes, here we are.
