### ISSUE TITLE
Symfony 6.3

### ISSUE THREAD

**Issue by pfpro** [shapecode/cron-bundle#56]
Hey there,
i try to switch from Symfony 6.2 to 6.3 and get the following logs:

`The "Shapecode\Bundle\CronBundle\EventListener\EntitySubscriber" class implements "Doctrine\Bundle\DoctrineBundle\EventSubscriber\EventSubscriberInterface" that is deprecated use the {@see AsDoctrineListener} attribute instead.
`

`Since symfony/doctrine-bridge 6.3: Registering "Shapecode\Bundle\CronBundle\EventListener\EntitySubscriber" as a Doctrine subscriber is deprecated. Register it as a listener instead, using e.g. the #[AsDoctrineListener] attribute.`

`User Deprecated: Since symfony/doctrine-bridge 6.3: Registering "Shapecode\Bundle\CronBundle\EventListener\EntitySubscriber" as a Doctrine subscriber is deprecated. Register it as a listener instead, using e.g. the #[AsDoctrineListener] attribute.`

Any chance you can fix the deprecations?

Best regards

**Comment by nicklog** [comment]
Hi,

it isnt an error. its just a deprecation.

Best regards

**Comment by pfpro** [comment]
I have adjusted the wording. is there still a chance that you will take care of the matter? in terms of a smooth transition to the current and upcoming symfony versions 6.3, 6.4, 7.0 and so on.
Hooray for shapecode!

**Comment by pfpro** [comment]
my log files are exploding ... could you give any further statement please?

**Comment by Gemorroj** [comment]
@nicklog 
> its just a deprecation.

yes, but it would be nice to fix it

**Comment by nicklog** [comment]
done
